version: 2
jobs:
  rust_and_cpp_build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: cd rust; make
      - run: cd c++; make
workflows:
  version: 2
  rust_and_cpp:
    jobs:
      - rust_and_cpp_build
