version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: cd rust; make
  test:
    docker:
        - image: circleci/rust:latest
    steps:
      - checkout
      - run: cd c++; make
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
